#!/bin/bash
set -euo pipefail
basedir="$(dirname "$0")/.."
name="$(basename "$0")"
dest="${basedir}/build/devel"
mkdir -p "$dest"
(cd "${basedir}" && ./bin/go build -ldflags="-s -w -buildid=" -o "$dest/${name}" "./cmd/${name}") && exec "$dest/${name}" "$@"
